In [2]:
#importing libraries
import cv2
import numpy as np
import face_recognition
import math
import os
from datetime import datetime

#getting all the images via list instead of manually declaring and putting them
path = '../ImageAttendance'
images = []
classNames = []

myList = os.listdir(path)
print(myList) 
for img in myList:
    curImg = cv2.imread(f'{path}/{img}')
    images.append(curImg)
    classNames.append(os.path.splitext(img)[0])
print(classNames)

#creating a function to get all the encodings of images in list
def findEncode(images):
    encodeList = []
    for col in images:
       col = cv2.cvtColor(col,cv2.COLOR_BGR2RGB)
       encodeImg = face_recognition.face_encodings(col)[0]
       encodeList.append(encodeImg)
    return encodeList
encodeListKnown = findEncode(images)
print(len(encodeListKnown))
print("ENCODING COMPLETE!")

def markAttendance(name):
    with open('attendance.csv','r+') as f:
        myDatalist = f.readlines()
        nameList=[]
        
        print(myDatalist)
        for line in myDatalist:
            entry = line.split(',')
            nameList.append(entry[0])
        if(name not in nameList):
            now = datetime.now()
            dateString = now.strftime('%H:%M:%S')
            f.writelines(f'\n{name},{dateString}')
    print(f"\n ------Your Entry Has Been Marked {name} ------\n")

            
    
# let us capture our image through web cam

cap = cv2.VideoCapture(0)
counter = 50
while counter:
    success,img = cap.read()
    imgS = cv2.resize(img,(0,0),None,0.25,0.25) #1/4 the size
    imgS = cv2.cvtColor(imgS,cv2.COLOR_BGR2RGB)
    
    facesCurFrame = face_recognition.face_locations(imgS) #there might be many faces hence we are locating all the faces and then encoding them
    encodesCurFrame = face_recognition.face_encodings(imgS,facesCurFrame)

    for encodeFace,faceLoc in zip(encodesCurFrame,facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown,encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown,encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)
        
        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(name)
            
            y1,x2,y2,x1 = faceLoc
            y1,x2,y2,x1 = y1*4,x2*4,y2*4,x1*4
            cv2.rectangle(img,(x1,y1),(x2,y2),2)
            cv2.rectangle(img,(x1,y1-35),(x2,y2),(0,255,0))
            cv2.putText(img,name,(x1+4,y2-4),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            markAttendance(name)
    cv2.imshow('Webcam',img)
    cv2.waitKey(1)
    
    

['billgates.jpg', 'dhanush.jpg', 'dhruv.jpg', 'jackma.jpg', 'jeff.jpg', 'sindhuja.jpg']
['billgates', 'dhanush', 'dhruv', 'jackma', 'jeff', 'sindhuja']
6
ENCODING COMPLETE!
[0.75886401 0.49091684 0.54005904 0.71908248 0.72467595 0.70353844]
DHANUSH
['Name,Time\n', '\n', 'DHANUSH,01:03:57\n', 'DHRUV,01:04:43']

 ------Your Entry Has Been Marked DHANUSH ------

[0.71983896 0.52891694 0.58572368 0.75084366 0.70185548 0.69338523]
DHANUSH
['Name,Time\n', '\n', 'DHANUSH,01:03:57\n', 'DHRUV,01:04:43']

 ------Your Entry Has Been Marked DHANUSH ------

[0.71769602 0.58433685 0.59511745 0.74038164 0.6877691  0.70827196]
DHANUSH
['Name,Time\n', '\n', 'DHANUSH,01:03:57\n', 'DHRUV,01:04:43']

 ------Your Entry Has Been Marked DHANUSH ------

[0.74712878 0.55096974 0.58595759 0.75195761 0.70726347 0.7350647 ]
DHANUSH
['Name,Time\n', '\n', 'DHANUSH,01:03:57\n', 'DHRUV,01:04:43']

 ------Your Entry Has Been Marked DHANUSH ------

[0.71779229 0.55657388 0.5846198  0.73104142 0.72012748 0.76916096]
DHA

KeyboardInterrupt: 

: 